#include "raylib.h"

#define SCREEN_WIDTH 1920
#define SCREEN_HEIGHT 1080

#define X_PIXELS_COUNT 50
#define Y_PIXELS_COUNT 50
#define PIXELS_COUNT (X_PIXELS_COUNT * Y_PIXELS_COUNT)

#define PIXEL_WIDTH 20
#define PIXEL_HEIGHT 20

#define BOARD_WIDTH (X_PIXELS_COUNT*PIXEL_WIDTH)
#define BOARD_HEIGHT (Y_PIXELS_COUNT*PIXEL_HEIGHT)

#define X_OFFSET (SCREEN_WIDTH - BOARD_WIDTH) / 2
#define Y_OFFSET (SCREEN_HEIGHT - BOARD_HEIGHT) / 2

#define MAP_STATES_COUNT 3