#include "raylib.h"

#define SCREEN_WIDTH 1920
#define SCREEN_HEIGHT 1080

#define GAME_SIZE 1000

#define PIXEL_SIZE 20
#define PIXEL_COUNT GAME_SIZE / PIXEL_SIZE
#define MAP_SIZE PIXEL_COUNT * PIXEL_COUNT

#define X_OFFSET (SCREEN_WIDTH - GAME_SIZE) / 2
#define Y_OFFSET (SCREEN_HEIGHT - GAME_SIZE) / 2